# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lazurde storefront CI

on:
  push:
    branches: [main, qa-testing, stage, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run test
      - run: npm run descriptors
      - run: npm run build
      # - uses: actions/checkout@v3
      # - name: Checking out to api tests repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: shopistan/lazurde-api-tests
      #     path: "./lazurde-api-tests"
      # - run: cd lazurde-api-tests && ls && npm i && cd postman_collections && newman run Lazurde.postman_collection.json --environment Lazurde.postman_environment.json
      # - name: Checking out to Ui/UX tests repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: shopistan/lazurde-ui-ux-automation-tests
      #     path: "./lazurde-ui-ux-automation-tests"
      # - run: cd lazurde-ui-ux-automation-tests && ls && yarn install && npx cypress run --headless
