# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lazurde storefront CI

on:
  push:
    branches: [main, qa-testing, stage, develop, LW-272-api-test-in-ci/cd]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: shopistan/lazurde-api-tests
          path: "./lazurde-api-tests"
      - run: ls
      - run: cd /public
      - run: ls
      # - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"
      # - run: npm i
      # - run: npm run test
      # - run: npm run descriptors
      # - run: npm run build
      # - run: cd
      # - run: ls
      # - run: git clone https://github.com/shopistan/lazurde-api-tests.git
      # - run: cd lazurde-api-tests
      # - run: yarn install
      # - run: cd Postman-Collections
      # - run: newman run Klondike_Collection.json --environment klondiketest.postman_environment.json
  #   path: main
  # with:
  # repository: 'https://github.com/shopistan/lazurde-api-tests'
